import { create } from 'zustand';
import type {
  EnhancedTranscriptChunk,
  TranscriptChunk,
  TranscriptError,
  TranscriptStatus,
} from '@/types/transcript';
import type { ResponseLanguageId } from '@lib/languages';
import { translateTranscript } from './transcriptTranslation.service';

export type TranscriptAvailability = 'available' | 'no-transcript' | 'unknown';
export type TranscriptViewMode = 'original' | 'translated';

interface TranscriptState {
  currentVideoId: string | null;
  chunks: TranscriptChunk[];
  enhancedChunks: EnhancedTranscriptChunk[];
  translatedChunks: EnhancedTranscriptChunk[];
  displayChunks: EnhancedTranscriptChunk[];
  filteredChunks: EnhancedTranscriptChunk[];
  status: TranscriptStatus;
  error: TranscriptError | null;
  availability: TranscriptAvailability;
  loading: boolean;
  translationLoading: boolean;
  translationError: string | null;
  language: string | null;
  isAutoGenerated: boolean;
  activeTime: number;
  activeChunkIndex: number;
  searchQuery: string;
  viewMode: TranscriptViewMode;
  translationLanguage: ResponseLanguageId | null;

  setVideoId: (videoId: string | null) => void;
  setSearchQuery: (query: string) => void;
  setTranscriptLoading: () => void;
  setTranscriptError: (error: TranscriptError) => void;
  setTranscriptNoAvailability: (reason?: string) => void;
  setTranscript: (payload: {
    videoId: string;
    chunks: TranscriptChunk[];
    enhancedChunks: EnhancedTranscriptChunk[];
    language: string;
    isAutoGenerated: boolean;
  }) => void;
  setActiveTime: (time: number, index: number) => void;
  setTranslationView: (mode: TranscriptViewMode) => void;
  loadTranslation: (targetLanguage: ResponseLanguageId) => Promise<void>;
}

function filterChunks(
  chunks: EnhancedTranscriptChunk[],
  query: string
): EnhancedTranscriptChunk[] {
  const q = query.trim().toLowerCase();
  if (!q) return chunks;
  return chunks.filter((c) => c.text.toLowerCase().includes(q));
}

function applyDisplay(
  enhancedChunks: EnhancedTranscriptChunk[],
  translatedChunks: EnhancedTranscriptChunk[],
  viewMode: TranscriptViewMode,
  searchQuery: string
): { displayChunks: EnhancedTranscriptChunk[]; filteredChunks: EnhancedTranscriptChunk[] } {
  const displayChunks =
    viewMode === 'translated' && translatedChunks.length ? translatedChunks : enhancedChunks;
  return {
    displayChunks,
    filteredChunks: filterChunks(displayChunks, searchQuery),
  };
}

const emptyState = {
  chunks: [] as TranscriptChunk[],
  enhancedChunks: [] as EnhancedTranscriptChunk[],
  translatedChunks: [] as EnhancedTranscriptChunk[],
  displayChunks: [] as EnhancedTranscriptChunk[],
  filteredChunks: [] as EnhancedTranscriptChunk[],
  status: 'idle' as TranscriptStatus,
  error: null as TranscriptError | null,
  availability: 'unknown' as TranscriptAvailability,
  loading: false,
  translationLoading: false,
  translationError: null as string | null,
  language: null as string | null,
  isAutoGenerated: false,
  activeTime: 0,
  activeChunkIndex: -1,
  searchQuery: '',
  viewMode: 'original' as TranscriptViewMode,
  translationLanguage: null as ResponseLanguageId | null,
};

export const useTranscriptStore = create<TranscriptState>((set, get) => ({
  currentVideoId: null,
  ...emptyState,

  setVideoId: (videoId) => {
    set({ currentVideoId: videoId, ...emptyState });
  },

  setSearchQuery: (query) => {
    const { displayChunks } = get();
    set({
      searchQuery: query,
      filteredChunks: filterChunks(displayChunks, query),
    });
  },

  setTranscriptLoading: () => {
    set({
      ...emptyState,
      status: 'loading',
      loading: true,
      currentVideoId: get().currentVideoId,
    });
  },

  setTranscriptError: (error) => {
    set({
      ...emptyState,
      status: 'error',
      error,
      currentVideoId: get().currentVideoId,
    });
  },

  setTranscriptNoAvailability: (reason) => {
    set({
      ...emptyState,
      status: 'no-transcript',
      availability: 'no-transcript',
      error: {
        type: 'not-available',
        message: reason ?? 'Transcript unavailable for this video',
      },
      currentVideoId: get().currentVideoId,
    });
  },

  setTranscript: ({ videoId, chunks, enhancedChunks, language, isAutoGenerated }) => {
    const q = get().searchQuery;
    const viewMode = get().viewMode;
    const translatedChunks = get().translatedChunks;
    const { displayChunks, filteredChunks } = applyDisplay(
      enhancedChunks,
      translatedChunks,
      viewMode,
      q
    );
    set({
      currentVideoId: videoId,
      status: 'success',
      error: null,
      availability: 'available',
      loading: false,
      chunks,
      enhancedChunks,
      displayChunks,
      filteredChunks,
      language,
      isAutoGenerated,
      activeTime: 0,
      activeChunkIndex: -1,
    });
  },

  setActiveTime: (time, index) => {
    set((state) => {
      const timeChanged = Math.abs(state.activeTime - time) > 0.25;
      const indexChanged = state.activeChunkIndex !== index;
      if (!timeChanged && !indexChanged) return state;
      return { ...state, activeTime: time, activeChunkIndex: index };
    });
  },

  setTranslationView: (mode) => {
    const { enhancedChunks, translatedChunks, searchQuery } = get();
    const { displayChunks, filteredChunks } = applyDisplay(
      enhancedChunks,
      translatedChunks,
      mode,
      searchQuery
    );
    set({ viewMode: mode, displayChunks, filteredChunks });
  },

  loadTranslation: async (targetLanguage) => {
    const { currentVideoId, enhancedChunks, language } = get();
    if (!currentVideoId || !enhancedChunks.length) return;

    if (get().translationLanguage === targetLanguage && get().translatedChunks.length) {
      get().setTranslationView('translated');
      return;
    }

    set({ translationLoading: true, translationError: null });
    try {
      const translated = await translateTranscript({
        videoId: currentVideoId,
        sourceChunks: enhancedChunks,
        targetLanguage,
        sourceLanguage: language ?? undefined,
      });
      const { searchQuery } = get();
      const { displayChunks, filteredChunks } = applyDisplay(
        enhancedChunks,
        translated,
        'translated',
        searchQuery
      );
      set({
        translatedChunks: translated,
        translationLanguage: targetLanguage,
        translationLoading: false,
        viewMode: 'translated',
        displayChunks,
        filteredChunks,
      });
    } catch (e) {
      set({
        translationLoading: false,
        translationError: e instanceof Error ? e.message : String(e),
      });
    }
  },
}));
