import { useCallback, useEffect, useRef } from 'react';
import { fetchTranscriptChunks } from '@/features/transcript/transcript.service';
import { findActiveChunkIndex } from '@/features/transcript/transcript.parser';
import { useTranscriptStore } from '@/features/transcript/transcript.store';
import { STUDYFLOW_EVENTS } from '@lib/constants';
import { getCurrentVideoId } from '@lib/youtube';

export function useTranscript(videoId: string) {
  const requestRef = useRef(0);
  const retryTimers = useRef<ReturnType<typeof setTimeout>[]>([]);

  const {
    setVideoId,
    setTranscriptLoading,
    setTranscript,
    setTranscriptError,
    setTranscriptNoAvailability,
    setActiveTime,
    status,
  } = useTranscriptStore();

  useEffect(() => {
    setVideoId(videoId);
  }, [videoId, setVideoId]);

  const loadTranscript = useCallback(async () => {
    if (!videoId) return;
    const capturedVideoId = videoId;

    const current = useTranscriptStore.getState();
    if (current.status === 'success' && current.currentVideoId === capturedVideoId && current.chunks.length) {
      return;
    }

    // Fast-path: Check IndexedDB cache before network fetch
    try {
      const { DbIds, ensureDbReady, getDb } = await import('@lib/db');
      await ensureDbReady();
      const cached = await getDb().transcripts.get(DbIds.transcript(capturedVideoId));
      if (cached && cached.chunks?.length && getCurrentVideoId() === capturedVideoId) {
        const rawChunks = cached.chunks.map((c) => ({
          id: c.id,
          text: c.text,
          start: c.startTime,
          end: c.endTime,
          duration: c.duration,
        }));
        const enhancedChunks = cached.chunks.map((c) => ({
          id: c.id,
          videoId: capturedVideoId,
          text: c.text,
          start: c.startTime,
          end: c.endTime,
          duration: c.duration,
          index: c.index,
        }));
        setTranscript({
          videoId: capturedVideoId,
          chunks: rawChunks,
          enhancedChunks,
          language: cached.language ?? 'en',
          isAutoGenerated: cached.isAutoGenerated ?? false,
        });
        console.log('[YT StudyFlow] Fast-path transcript loaded from IndexedDB:', {
          videoId: capturedVideoId,
          chunkCount: enhancedChunks.length,
        });
        return;
      }
    } catch {
      // Fallback to network fetch
    }

    const requestId = ++requestRef.current;
    if (current.status !== 'loading') {
      setTranscriptLoading();
    }

    console.log('[YT StudyFlow] Invoking fetchTranscriptChunks network pipeline for:', capturedVideoId);
    const result = await fetchTranscriptChunks(capturedVideoId);
    if (requestId !== requestRef.current) return;
    if (getCurrentVideoId() !== capturedVideoId) return;

    if (result.status === 'success') {
      setTranscript({
        videoId: capturedVideoId,
        chunks: result.chunks,
        enhancedChunks: result.enhancedChunks,
        language: result.metadata.language,
        isAutoGenerated: result.metadata.isAutoGenerated,
      });
      console.log('[YT StudyFlow] State updated: TRANSCRIPT_LOADED_SUCCESS', {
        videoId: capturedVideoId,
        chunkCount: result.chunks.length,
        enhancedCount: result.enhancedChunks.length,
        language: result.metadata.language,
      });
    } else if (result.status === 'not-available') {
      const again = useTranscriptStore.getState();
      if (again.status === 'success' && again.chunks.length) return;
      if (getCurrentVideoId() !== capturedVideoId) return;
      setTranscriptNoAvailability(result.reason);
      console.warn('[YT StudyFlow] State updated: TRANSCRIPT_NO_AVAILABILITY', {
        videoId: capturedVideoId,
        reason: result.reason,
      });
      return;
    } else {
      const again = useTranscriptStore.getState();
      if (again.status === 'success' && again.chunks.length) return;
      if (getCurrentVideoId() !== capturedVideoId) return;
      setTranscriptError({ type: 'unknown', message: result.reason });
      console.error('[YT StudyFlow] State updated: TRANSCRIPT_ERROR', {
        videoId: capturedVideoId,
        reason: result.reason,
      });
      return;
    }

    try {
      if (getCurrentVideoId() !== capturedVideoId) return;
      const { DbIds, ensureDbReady, getDb, nowMs } = await import('@lib/db');
      await ensureDbReady();
      const ts = nowMs();
      await getDb().transcripts.put({
        id: DbIds.transcript(capturedVideoId),
        videoId: capturedVideoId,
        language: result.metadata.language,
        isAutoGenerated: result.metadata.isAutoGenerated,
        metadata: {
          totalDuration: result.totalDuration,
          chunkCount: result.enhancedChunks.length,
          fetchedAt: result.metadata.fetchedAt,
        },
        chunks: result.enhancedChunks.map((c) => ({
          id: c.id,
          text: c.text,
          startTime: c.start,
          endTime: c.end,
          duration: c.duration,
          index: c.index,
        })),
        createdAt: ts,
        updatedAt: ts,
        schemaVersion: 1,
      });
    } catch {
      // non-fatal
    }
  }, [
    videoId,
    setTranscript,
    setTranscriptError,
    setTranscriptLoading,
    setTranscriptNoAvailability,
  ]);

  useEffect(() => {
    retryTimers.current.forEach(clearTimeout);
    retryTimers.current = [];

    void loadTranscript();

    // Player/captions may load after sidebar — retry with backoff only if idle/error (skip if already success or loading)
    for (const delay of [2500, 6000, 12000]) {
      retryTimers.current.push(
        setTimeout(() => {
          const s = useTranscriptStore.getState();
          if (s.status === 'success' && s.chunks.length) return;
          if (s.status === 'loading') return;
          if (getCurrentVideoId() !== videoId) return;
          console.log(`[TRANSCRIPT DEBUG] RETRY_BACKOFF_TRIGGERED | videoId:${videoId} | delay:${delay}ms`);
          void loadTranscript();
        }, delay)
      );
    }

    return () => {
      retryTimers.current.forEach(clearTimeout);
    };
  }, [videoId, loadTranscript]);

  useEffect(() => {
    const onTime = (e: Event) => {
      const detail = (e as CustomEvent<{ currentTime: number; videoId: string }>).detail;
      if (!detail || detail.videoId !== videoId) return;

      const chunks = useTranscriptStore.getState().enhancedChunks;
      const index = findActiveChunkIndex(chunks, detail.currentTime);
      setActiveTime(detail.currentTime, index);
    };

    window.addEventListener(STUDYFLOW_EVENTS.TIME_UPDATE, onTime);
    return () => window.removeEventListener(STUDYFLOW_EVENTS.TIME_UPDATE, onTime);
  }, [videoId, setActiveTime]);

  return { loadTranscript, status };
}
